# Generated by Django 5.0 on 2025-11-04 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        ("menus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="foodorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foodorderitem",
            name="food_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menus.foodorder",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "vendor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_menus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="menus.menucategory",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="menus.menu",
            ),
        ),
        migrations.AddField(
            model_name="foodorderitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="menus.menuitem",
            ),
        ),
        migrations.AddIndex(
            model_name="foodorder",
            index=models.Index(
                fields=["order_number"], name="menus_foodo_order_n_85f44e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodorder",
            index=models.Index(
                fields=["user", "status"], name="menus_foodo_user_id_fcc78e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodorder",
            index=models.Index(
                fields=["event", "status"], name="menus_foodo_event_i_8ca823_idx"
            ),
        ),
    ]
