# Generated by Django 5.0 on 2025-11-04 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailnotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotification",
            index=models.Index(
                fields=["recipient", "notification_type"],
                name="notificatio_recipie_02bb5c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailnotification",
            index=models.Index(
                fields=["event", "notification_type"],
                name="notificatio_event_i_8e65dd_idx",
            ),
        ),
    ]
